language: node_js

node_js:
  - "8"
  - "7"
  - "6"
  - "5"

cache:
  directories:
    - "node_modules"

install:
  - npm install

script:
  - npm run flow-typed install
  - npm run flow
  - npm run lint
  - npm test

after_success:
  - npm run report:coveralls
